# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd5691fffd4bca7f92b001521057fd4deed7241a59c3ffaafc571bf441b886c214763a1a22e6ecd37af80ace748cf5af74016a1ffc065c2549eb0f40e448529

test:
  secret_key_base: 05dcbdf59313c05d300605fe2d6d32a5dea267b239d16eadaa8ed9beb834e2f26656640b19e6a21368bd8cf01a2ecf85d1c915e3463e0dbb9fddb6965655b5cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
